### ISSUE TITLE
consistently use CC-BY-SA or less material, correctly attribute and double check all material

### ISSUE THREAD

**Issue by joergbrech** [joergbrech/Modellbildung-und-Simulation#166]
We have to make sure that all used resources are licensed under CC-By-SA or a less restrictive CC license and that we consistently and correctly attribute the copyright and licensing of the resource. 

 - [x] Discuss how to deal with embedded videos/gifs.
 - [x] Create a list of all resources (images, videos, embedded stuff)
 - [x] Add a CC-XXX license to own material

**Comment by joergbrech** [comment]
We should add a Markdown file to this repo that contains a table listing all used resources with their license and author information.

**Comment by JasminBreuer** [comment]
Embedded videos that do not have a CC license must be marked with a note (see page 128 of https://www.was-ist-oer.de/wp-content/uploads/sites/17/2018/01/Joeran-Muuss-Merholz-Freie-Unterrichtsmaterialien-Beltz-2018.pdf).
An issue has been created for this purpose.

Own images must each be marked with a license notice below using TULLU.
Since the whole work has a CC-BY-SA licensing, images can be licensed as CC0, CC-BY or CC-BY-SA. 
To make our own images even more usable to other people, we recommend to publish these images on Flickr and then link from our book to it (Flickr as image source).
