### ISSUE TITLE
Update .gitignore?

### ISSUE THREAD

**Issue by PhiSpel** [joergbrech/Modellbildung-und-Simulation#268]
Every now and then, Octave code boxes with `%%file [filename].m` keyword are added. Do the they need to be added to .gitignore? Should we add this to the Style/Contributing Guideline?

**Comment by PhiSpel** [comment]
@joergbrech, do you know something about this?

**Comment by joergbrech** [comment]
I am okay with adding them to the `.gitignore` file. Since those files are generated automatically, they should not be part of version control.

I suppose we could also add this to the contribution guide, but I am a bit worried that it might be off-putting if our contribution guide grows into an ever increasing list of To-Dos. Contribution should stay easy and fun! What does everybody else think?

**Comment by PhiSpel** [comment]
As noone else thought soemthing about this, all I did was:

1. keyword search for `%%file` via github
2. added all found files to `.gitignore`
3. removed all other `.m`-files in `.gitignore`. These were:

- bisection.m
- fibonacci.m
- global_variables.m
- increment_a.m
- myScript.m
- mylittlefarm.m
- oldmcdonald.m
- resonance_catastrophe.m
- xralkldaf.m
- sphericalGrid.m
- spherical2Cartesian.m
- rxlquapoeh.m
- binomial_coefficient.m
- F.m 
- minimize.m
- rod_frequency.m
- fourier_approx_sawtooth.m
- vuvuzela_filter_* (there is only a static `vuvuzela_filter.m` file at the moment)
